'''
Created By:
Created On:
Last Modified By:
Last Modified On:
Course:
Assignment:
Purpose:
'''

# Imports used for hashing functions, time keeping, and iterating efficiently.
import hashlib, time, itertools

# A password cracker that accepts an MD5 hash and prints the password to the screen
class PasswordCracker:

	# Creates instance of the PasswordCracker object
	# self - This instance of PasswordCracker
	# digest - The MD5 hex digest to be cracked
	def __init__(self, digest):
		self.banner()
		self.hash = digest

	# Cracks the digest that the object was instantiated with
	# self - This instance of PasswordCracker
	def crack(self):
		print("Not yet implemented")
		return

	# Prints out the password cracker's banner (generated by http://patorjk.com/software/taag/).
	def banner(self):
	    print("     ______                __              ")
	    print("    / ____/________ ______/ /_____  _____  ")
	    print("   / /   / ___/ __ `/ ___/ //_/ _ \/ ___/  ")
	    print("  / /___/ /  / /_/ / /__/ ,< /  __/ /      ")
	    print("  \____/_/   \__,_/\___/_/|_|\___/_/       \n")
