'''
Created By:
Created On:
Last Modified By:
Last Modified On:
Course:
Assignment:
Purpose:
'''

# Imports used for hashing functions, file functions,
# sys calls, and converting between ascii and hex.
import hashlib, os, sys, binascii

# A file carver that accepts a binary and writes all discovered files to
# the specified output directory
class FileCarver:

	# Creates instance of the FileCarver object
	# self - This instance of FileCarver
	# inputFile - Binary to be parsed
	# output - Destination directory for carved files to be written to
	def __init__(self, inputFile, output):
		self.banner()
		self.iFile = inputFile
		self.oDest = output

	# Carves the binary that the object was instantiated with
	# self - This instance of FileCarver
	def carve(self):
		print("Not yet implemented")
		return

	# Prints out the file carver's banner (generated by http://patorjk.com/software/taag/).
	def banner(self):
		print("   (                                ")
		print("   )\      )  (     )      (   (    ")
		print(" (((_)  ( /(  )(   /((    ))\  )(   ")
		print(" )\___  )(_))(()\ (_))\  /((_)(()\  ")
		print("((/ __|((_)_  ((_)_)((_)(_))   ((_) ")
		print(" | (__ / _` || '_|\ V / / -_) | '_| ")
		print("  \___|\__,_||_|   \_/  \___| |_|   ")
